version: '3'
services:
  hospitalemergency:
    build: ./src
    stdin_open: true
    tty: true
    ports:
      - 5000:5000
    command: /bin/bash
    # environment:
    #   NVIDIA_VISIBLE_DEVICES: 0
    #   CUDA_VISIBLE_DEVICES: 0
    ulimits:
      memlock: -1
    shm_size: '16gb'
    volumes:
      - ./src:/src
    ipc: "host"
