# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /src

# Copy the requirements file into the container
COPY . /src

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r /src/requirements.txt

# Specify the command to run on container start
CMD ["/bin/bash"]